set(SDKCONFIG_DEFAULTS
    ${SDKCONFIG_DEFAULTS}
    ESP32_GENERIC_S3/sdkconfig.flash_4m
)

list(APPEND MICROPY_DEF_BOARD
    MICROPY_HW_BOARD_NAME="Generic ESP32S3 module 4MB flash"
)

set(MP_DL_FACE_DETECTOR_ENABLED 1)
