name: ESP32

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'src/**'
      - '.github/workflows/*.yml'
      - 'boards/**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MICROPYTHON_VERSION: v1.27.0
  MICROPYTHON_DIR: /home/runner/micropython
  ESP_IDF_DIR: /home/runner/esp-idf
  ARTIFACTS_DIR: /home/runner/artifacts
  MP_CAMERA_DIR: /home/runner/micropython-camera-API
  MP_JPEG_DIR: /home/runner/mp_jpeg
  ESP32_CAMERA_DIR: /home/runner/esp32-camera

jobs:
  setup-environment:
    runs-on: ubuntu-24.04
    steps:
      - name: Cache ESP-IDF and MicroPython
        id: cache_esp_idf
        uses: actions/cache@v4
        with:
          lookup-only: true
          path: |
            ${{ env.ESP_IDF_DIR }}
            ~/.espressif/
            ~/.cache/pip/
            ${{ env.MICROPYTHON_DIR }}
          key: mpy-${{ env.MICROPYTHON_VERSION }}-idf-v5.4.2-r2

      - name: Install dependencies (if not cached)
        if: steps.cache_esp_idf.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

      - name: Clone pinned MicroPython release (if not cached)
        if: steps.cache_esp_idf.outputs.cache-hit != 'true'
        run: |
          cd ~
          git clone --depth 1 --branch ${{ env.MICROPYTHON_VERSION }} https://github.com/micropython/micropython.git ${{ env.MICROPYTHON_DIR }}
          cd ${{ env.MICROPYTHON_DIR }}
          git submodule update --init --depth 1
          cd mpy-cross && make

      - name: Set up ESP-IDF
        if: steps.cache_esp_idf.outputs.cache-hit != 'true'
        run: |
          cd ~
          # git clone --depth 1 --branch release/v5.4 https://github.com/espressif/esp-idf.git ${{ env.ESP_IDF_DIR }}
          git clone --depth 1 --branch v5.4.2 https://github.com/espressif/esp-idf.git ${{ env.ESP_IDF_DIR }}
          git -C ${{ env.ESP_IDF_DIR }} submodule update --init --recursive --filter=tree:0
          cd ${{ env.ESP_IDF_DIR }} && ./install.sh esp32s3
          source ./export.sh
          make -C ${{ env.MICROPYTHON_DIR }}/ports/esp32 BOARD=ESP32_GENERIC_S3 submodules

  build:
    needs: setup-environment
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        board:
          - ESP32_GENERIC_S3-FLASH_16M_PEDESTRIAN

    steps:
      - name: Cache ESP-IDF and MicroPython
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.ESP_IDF_DIR }}
            ~/.espressif/
            ~/.cache/pip/
            ${{ env.MICROPYTHON_DIR }}
          key: mpy-${{ env.MICROPYTHON_VERSION }}-idf-v5.4.2-r2

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build MicroPython
        run: |
          source ${{ env.ESP_IDF_DIR }}/export.sh
          git -C ${{ env.MICROPYTHON_DIR }} apply --check ${{ github.workspace }}/patches/micropython-v1.27-tinyusb.patch
          git -C ${{ env.MICROPYTHON_DIR }} apply ${{ github.workspace }}/patches/micropython-v1.27-tinyusb.patch
          git clone --depth 1 https://github.com/cnadler86/micropython-camera-API.git ${{ env.MP_CAMERA_DIR }}
          git clone --depth 1 https://github.com/cnadler86/mp_jpeg.git ${{ env.MP_JPEG_DIR }}
          git clone --depth 1 https://github.com/cnadler86/esp32-camera.git ${{ env.ESP32_CAMERA_DIR }}
          
          cd ${{ github.workspace }}/boards/
          
          # Check if a variant is defined and adjust the idf.py command
          IFS='@' read -r BUILD_TARGET CAMERA_MODEL <<< "${{ matrix.board }}"
          IFS='-' read -r BOARD_NAME BOARD_VARIANT <<< "${BUILD_TARGET}"

          IDF_CMD="idf.py -DMICROPY_DIR=${{ env.MICROPYTHON_DIR }} -DMP_CAMERA_DIR=${{ env.MP_CAMERA_DIR }} -DMP_JPEG_DIR=${{ env.MP_JPEG_DIR }} -DMICROPY_BOARD=$BOARD_NAME -B build-$BUILD_TARGET"
          if [ -n "${BOARD_VARIANT}" ]; then
              IDF_CMD="$IDF_CMD -DMICROPY_BOARD_VARIANT=$BOARD_VARIANT"
          fi
          if [ -n "${CAMERA_MODEL}" ]; then
            echo "FW_NAME=${CAMERA_MODEL}" >> $GITHUB_ENV
            FINAL_CMD="${IDF_CMD} -DMICROPY_CAMERA_MODEL=${CAMERA_MODEL} build"
          else
            echo "FW_NAME=${BUILD_TARGET}" >> $GITHUB_ENV
            FINAL_CMD="${IDF_CMD} build"
          fi
          
          eval "$FINAL_CMD"

          cd build-$BUILD_TARGET
          python ${{ env.MICROPYTHON_DIR }}/ports/esp32/makeimg.py sdkconfig bootloader/bootloader.bin partition_table/partition-table.bin micropython.bin firmware.bin micropython.uf2
          
          mkdir -p ${{ env.ARTIFACTS_DIR }}
          mv firmware.bin ${{ env.ARTIFACTS_DIR }}/firmware-$BUILD_TARGET.bin

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ env.MICROPYTHON_VERSION }}-${{ env.FW_NAME }}
          path: ${{ env.ARTIFACTS_DIR }}/**
          retention-days: 5

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.board }}
          path: |
            ${{ github.workspace }}/boards/build-${{ matrix.board }}/log/
          retention-days: 5
